set(CPACK_GENERATOR "DEB")

set(CPACK_PACKAGE_NAME "osqp")
set(CPACK_PACKAGE_VERSION "${OSQP_VERSION}")
# Map CMAKE_SYSTEM_PROCESSOR to Debian-compatible architecture
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
else()
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")
endif()
set(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}"
)
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libeigen3-dev (>= 3.4.0), libblas3 (>= 3.10.0), liblapack3 (>= 3.10.0)")

set(CPACK_PACKAGE_VENDOR "gunjae-yoon")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The Operator Splitting QP Solver")
set(CPACK_PACKAGE_CONTACT "gjyoon@plaif.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Gunjae Yoon")

include(CPack)